# Generated by Django 5.0 on 2024-01-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99)),
                ('tipo', models.CharField(max_length=20)),
                ('unidad', models.CharField(max_length=20)),
                ('precio_unidad', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=99)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('compras', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99)),
                ('cuit', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('insumos', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Restaurantes',
        ),
    ]
